Sprint 1/step 2
praktikumalexey/reactjs pull request #2
Opened 2021-08-29 11:22 UTC by praktikumalexey

Add landing for first sprint

2021-08-30 11:35 UTC, SmilingJey commented
Здравствуйте 

Не реализована обязательная часть этого этапа работы - попапы ингредиента и заказа

Сейчас работа отклоняется от проверки

2021-09-05 15:39 UTC, SmilingJey requested changes
Здравствуйте

Хорошая работа! Приложение почти полностью соответсвует макету, декомпозировано на компоненты, правильно используются компоненты из библиотеки, код хорошо организован и оформлен, работает закрытие по ESC и оверлею. Но есть небольшое замечание, которое нужно исправить:

**Нужно исправить:**

- перенесите компонент App в соответствующую папку в папке components

- вынесите базовый адрес сервера https://norma.nomoreparties.space/api сервера в константу

- добавьте проверку ответа сервера при запросе

- оберните иконку и текст в ссылку в шапке в ссылку `<a href="#">`, а не кнопку, отображение не соответствует макету

- отображение конструктора не соответствует макету

- разместите в компонентах  OrderDetails и IngredientDetails только содержимое попапа

- не нужно передавать условие открытия в попап и размещать логику открытия в самом Modal

- по заданию должен быть компонент ModalOverlay, оверлей должен быть полупрозрачного темного цвета, а не светлого

**Можно лучше**

- отображение скролов отличается списка ингредиентов и конструктора от макета, задайте соответствующие стили

- файл стилей лучше называть не style.module.css, а в соответсвии с названием компонента, например BurgerIngredients.module.css 

**Более подробно эти и более мелкие мелкие замечания, а так же места в которых можно улучшить проект, отмечены в коде:**

2021-09-05 15:39 UTC, SmilingJey commented on src/App.tsx
> +    fetch("https://norma.nomoreparties.space/api/ingredients")
**Надо исправить**

вынесите базовый адрес сервера `https://norma.nomoreparties.space/api` сервера в константу в отдельный файл, а адрес эндпоинта можно оставить в самой функции запроса `${BURGER_API_URL}/ingredients`

**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2021-09-05 15:39 UTC, SmilingJey commented on src/App.tsx
> +      .then((response) => response.json())
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2021-09-05 15:39 UTC, SmilingJey commented on src/App.tsx
> +function App(): React.ReactElement {
**Надо исправить**

перенесите компонент App в соответствующую папку в папке components

2021-09-05 15:39 UTC, SmilingJey commented on src/components/AppHeader/HeaderButton/index.tsx
> +    <Button type="primary">
**Надо исправить**

Оберните иконку и текст в ссылку в шапке в ссылку `<a href="#">`, а не кнопку

В следующих спринтах вместо ссылки будет компонент Link из библиотеки react router, а пока сделайте просто ссылкой

Так же нужно исправить отображение, сейчас оно не соответвует макету

2021-09-05 15:39 UTC, SmilingJey commented on src/components/BurgerConstructor/OrderDetails.tsx
> +    <Modal caption="" isOpen={props.isOpen} onClose={props.onClose}>
**Надо исправить**

разместите в компоненте OrderDetails только содержимое попапа

2021-09-05 15:39 UTC, SmilingJey commented on src/components/BurgerConstructor/Constructor.tsx
> +  const listItems = props.ingredients.map((item: TIngredient) => (
**Надо исправить**

отображение конструктора не соответствует макету

 Первым и последним элементами должна быть одинаковая булка, элементы откличаются скруглением. У у ингредиентов внутри бургера должно быть симметричное скругление, а слева находится элемент с точками, который говорит, что элемент можно перетаскивать (перетаскивание будет реализовано на следующем спринте)

Сверьтесь с макетом

2021-09-05 15:39 UTC, SmilingJey commented on src/components/BurgerIngredients/index.tsx
> +const ingredientsGroup = (ingredients: Array<TIngredient>): TGroupIngredietnts => {
**Надо исправить**

функции следует называть начиная с глагола

2021-09-05 15:39 UTC, SmilingJey commented on src/components/BurgerIngredients/IngredientDetails.tsx
> +export const IngredientDetails = (props: {
**Надо исправить**

оставьте в компоненте IngredientDetails только содержимое попапа, т.к. в 3 спринте понадобится сделать страницу с точно таким же содержимым и нужно для этого будет переиспользовать компонент IngredientDetails

2021-09-05 15:39 UTC, SmilingJey commented on src/components/BurgerIngredients/index.tsx
> +      <IngredientDetails onClose={closeDetails} ingredient={detailIngredients} />
**Надо исправить**

согласно замечанию в IngredientDetails и Modal здесь будет выглядеть так:

```
 { props.ingredient !== null && (<Modal
      caption="Детали ингредиента"
      onClose={closeDetails}
    >
        <IngredientDetails ingredient={detailIngredients} />
   </Modal>
)}
```

2021-09-05 15:39 UTC, SmilingJey commented on src/components/Modal/index.tsx
> +      {isOpen && (
**Надо исправить**

не нужно передавать условие открытия в попап и размещать логику открытия в самом Modal. Рендерите компонент попапа только, если он открыт, используя для этого условный рендеринг

```
{isOpen && (
    компонент открываемого попапа
)}
``

2021-09-05 15:39 UTC, SmilingJey commented on src/components/Modal/index.tsx
> +        <Portal className={"modal"}>
**Надо исправить**

по заданию должен быть компонент ModalOverlay

2021-09-05 15:39 UTC, SmilingJey commented on src/components/Modal/index.tsx
> +          <div ref={modalOverlay} className={style.modal}>
**Надо исправить**

по макету оверлей должен быть не светлого, а темного цвета rgb(0,0,0, 0.2)

2021-09-05 15:39 UTC, SmilingJey commented on src/components/BurgerConstructor/index.tsx
> +      <OrderDetails id={orderId} isOpen={openOrder} onClose={closeDetails} />
**Надо исправить**

согласно замечанию в OrderDetails и Modal здесь будет выглядеть так:

```
 {openOrder && (<Modal
      caption=""
      onClose={closeDetails}
    >
        <OrderDetails id={orderId}  />
   </Modal>
)}
```

2021-09-06 18:02 UTC, praktikumalexey commented on src/components/Modal/index.tsx
> +        <Portal className={"modal"}>
Тут немного сомнительно по поводу портала и ModalOverlay. Но ок.

2021-09-06 18:04 UTC, praktikumalexey commented on src/components/AppHeader/HeaderButton/index.tsx
> +    <Button type="primary">
Ок, но link можно использовать с любым элементов =)

2021-09-06 18:13 UTC, pan-alexey commented on src/components/BurgerConstructor/OrderDetails.tsx
> +    <Modal caption="" isOpen={props.isOpen} onClose={props.onClose}>
ИМХО Удобней использовать компонент с модалкой, а не хранить логику открытия модалки внутри компонента - это помогает абстрагировавать компонент и декомпозировать логику

2021-09-06 18:14 UTC, pan-alexey commented on src/components/Modal/index.tsx
> +      {isOpen && (
Опять таки - имхо - декомпозировать логику открытия модалки внутри компонента удобнее

2021-09-06 18:15 UTC, pan-alexey commented on src/components/BurgerConstructor/index.tsx
> +      <OrderDetails id={orderId} isOpen={openOrder} onClose={closeDetails} />
Тут то же самое, логика должна соержаться внутри компонента Details.

2021-09-06 18:16 UTC, pan-alexey commented on src/App.tsx
> +    fetch("https://norma.nomoreparties.space/api/ingredients")
В задании это не указанно, но ок.

2021-09-06 18:42 UTC, pan-alexey commented on src/components/BurgerIngredients/index.tsx
> +const ingredientsGroup = (ingredients: Array<TIngredient>): TGroupIngredietnts => {
Fix

2021-09-06 18:43 UTC, pan-alexey commented on src/App.tsx
> +    fetch("https://norma.nomoreparties.space/api/ingredients")
Fix

2021-09-06 18:43 UTC, pan-alexey commented on src/components/AppHeader/HeaderButton/index.tsx
> +    <Button type="primary">
fix

2021-09-06 18:44 UTC, pan-alexey commented on src/components/Modal/index.tsx
> +      {isOpen && (
Тот же поинт - логика модалки (открытия/закрытия) хранится в модалке

2021-09-06 18:45 UTC, pan-alexey commented on src/components/BurgerIngredients/index.tsx
> +      <IngredientDetails onClose={closeDetails} ingredient={detailIngredients} />
Не согласен, логика должна быть в модалке

2021-09-06 18:58 UTC, praktikumalexey commented on src/components/BurgerConstructor/Constructor.tsx
> +  const listItems = props.ingredients.map((item: TIngredient) => (
fix

2021-09-07 08:37 UTC, SmilingJey commented on src/api/ingredients.ts
> +        alert("Ошибка ответа сервера, перезагрузите страницу");
**Надо исправить**

оставьте обработку ошибок в блоке catch, не у всех запросов нужно выводить это предупреждение

```
    getIngredients().then(({ data }) => {
      setIngredients(data);
    })
   .catch(() => {
       alert("Ошибка ответа сервера, перезагрузите страницу");
   })
```

2021-09-07 08:37 UTC, SmilingJey commented on src/api/ingredients.ts
> +        Promise.reject(err);
**Надо исправить**

здесь нужен return , без возврата промис не будет отклонен

2021-09-07 08:37 UTC, SmilingJey commented on src/components/AppHeader/HeaderButton/index.tsx
> +      <Button type="primary">
**Надо исправить**

размещать кнопку внутри ссылки не имеет смысла
![2021-09-07_11-45-10](https://user-images.githubusercontent.com/9317133/132314327-8db6da1c-b8ee-4577-93a0-48c33cb8ca39.png)



Шапка сайта все так же не соответствует макету

Сейчас:
![2021-09-07_10-53-46](https://user-images.githubusercontent.com/9317133/132306585-0d4983cc-f909-4482-b68b-d2964bebf3bc.png)


Макет:
![2021-09-07_10-55-21](https://user-images.githubusercontent.com/9317133/132306681-7ea3e11b-446e-4b71-90ff-4a94b0c54402.png)

2021-09-07 08:37 UTC, SmilingJey commented on src/components/BurgerConstructor/Constructor.tsx
> +  const listItems = props.ingredients.map((item: TIngredient, i: number) => (
**Надо исправить**

отображение конструктора все ещё отличается от макета, у первого и последнего элемента нет точек

Сейчас:
![2021-09-07_10-57-15](https://user-images.githubusercontent.com/9317133/132307401-aaf90503-d73c-4852-a846-6ee710942e44.png)

Макет:
![2021-09-07_10-57-47](https://user-images.githubusercontent.com/9317133/132307434-b855fded-a204-4126-8b83-d2d0b1649371.png)

2021-09-07 08:37 UTC, SmilingJey commented on src/components/BurgerIngredients/IngredientDetails.tsx
> +export const IngredientDetails = (props: {
оставьте так, на 3 спринте все равно придется исправить

2021-09-07 08:42 UTC, SmilingJey commented on src/components/Modal/index.tsx
> +      {isOpen && (
Не согласен с вашей логикой, если компонент не отображается то его не нужно рендерить
Сейчас компонент попадает в дерево реакта, даже если попап закрыт

![2021-09-07_11-38-18](https://user-images.githubusercontent.com/9317133/132313612-67d37033-f638-4ba1-8844-b3383fa21131.png)

Но можете оставить так

2021-09-07 08:49 UTC, SmilingJey requested changes
Большая часть замечаний исправлена, но несколько ещё осталось

- при проверке ответа сервера должен быть возврат отклоненного промиса

- поместите обработку ошибок в блоке catch, не у всех запросов нужно выводить предупреждение

- в шапке кнопка не должна оборачиваться в ссылку

-  шапка и конструктор бургера не соответствуют макету

Управление модальным окном можете оставить в Modal, но как я отметил выше это не совсем корректно

2021-09-07 13:58 UTC, praktikumalexey commented on src/api/ingredients.ts
> +        Promise.reject(err);
Точно, опечатался

2021-09-08 06:31 UTC, SmilingJey approved these changes
Отлично, замечание по проверке ответа сервера и отображение конструктора исправлено

Но не забудьте убрать бэкграунд у кнопок в шапке, что бы отображение соответствовало макету

Успехов в дальнейшем обучении!

2021-09-08 06:31 UTC, SmilingJey commented on src/components/AppHeader/HeaderButton/style.module.css
> +  background: linear-gradient(63.18deg, #801ab3 0%, #4c4cff 100%);
**Надо исправить**

уберите этот бэкграунд, его нет по макету

2021-09-08 17:52 UTC, merged